# Generated by Django 5.0.3 on 2024-05-23 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240524_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.endpoint'),
        ),
    ]
