# Generated by Django 5.0.3 on 2024-05-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_event_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='custom_js',
            field=models.TextField(blank=True, null=True),
        ),
    ]
