# Generated by Django 5.0.3 on 2024-05-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_endpoint_custom_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Add your custom tracking JavaScript here. Only safe JavaScript is allowed.', null=True),
        ),
    ]
