# Generated by Django 5.0.3 on 2024-05-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='session_id',
            field=models.CharField(default='default_session_id', max_length=50),
        ),
    ]
