# Generated by Django 5.0.3 on 2024-05-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.CharField(max_length=50),
        ),
    ]
